# This workflow will thoroughly test the build system
name: Complete build system test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends git make pkg-config
        sudo apt-get install --no-install-recommends inkscape optipng
        sudo apt-get install --no-install-recommends libgomp1 libglm-dev libglfw3-dev libglew-dev libstb-dev libtinyobjloader-dev

    - name: Test icons build correctly
      run: |
        make icons

    - name: Test the shared library builds
      run: |
        make library -j$(nproc)

    - name: Test demo builds
      run: |
        make build -j$(nproc)

    - name: Test demo builds from fresh in debug mode
      run: |
        make debug -j$(nproc)

    - name: Test built library installs
      run: |
        ls build/demo build/libammonite.so

    - name: Test built library installs
      run: |
        sudo make install

    - name: Test library headers install
      run: |
        sudo make headers
